### ISSUE TITLE
take match score into account when computing ELO gains and losses

### ISSUE THREAD

**Issue by gaetancombes** [yassineAlouini/melo#1]
Right now the outcome is either `win` or `lose`. 

Add more possible outputs depending on the final score of the game so that winning with a 10-8 score will give less points than a perfect 10-0 game for example

**Comment by yassineAlouini** [comment]
That's a very good remark.  I propose adding a multiplicative constant G that is equal to the difference of goals  (would be 10 if one team scored 10 and the other 0 or 9 and the other -1) score to adjust the new score: 

R_n = R_o + K G (W - W_e)

Where R_n is the new elo, R_o is the previous elo, W is the score and W_e the expected score.

**Comment by yassineAlouini** [comment]
It has been implemented. :tada:
